### PR TITLE
Added main elements of Youtube page

### PR DESCRIPTION
**Pull request by bettercallazamat**
Main elements added such as:
1. Logo in navbar
2. Searchbar in navbar
3. Supportive buttons in navbar(upload, sing-in, notifications)
4. Embedded video
5. Video related info (title, owner, views)
6. Video related buttons (subscribe, like, dislike, share, etc)
7. Recomended videos on right side of the page

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really great job @bettercallazamat and @bertil291utn !
You've come a long way making all this happen, congrats :medal_military: Please consider my comments below and make the required changes to bring the project up to Microverse standards :100: I wish you all the best and see you at the top! :rocket: 

#### Navigation
Please consider giving your navigation bar second looks, I have attached screenshots of the necessary requirements below as well as your current navigation bar and finally what it should look like
* Requirements
screenshot

* Where you are
screenshot

* What you should end up with
screenshot

#### Video Controls
Please consider giving your navigation bar second looks, I have attached screenshots of the necessary requirements below as well as your current navigation bar and finally what it should look like
* Requirements
screenshot

* Where you are
screenshot

* What you should end up with
screenshot

### Summary
You've done really nicely, building this all out and you have just a few more changes to make as I have listed above. Please make these necessary adjustments and request another review :ok_hand: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hey team :wave: 
I can see that you made an attempt to incoporate the changes I suggested in the last review, however, please consider looking closely at the screenshots or the original site itself as the main video controls are still not arranged properly and at the moment your nav bar icons are incomplete and not showing up.

Make these changes and request another review! I wish you the best and see you at the top :1st_place_medal: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job @bettercallazamat and @bertil291utn!
Your project looks really perfect, the only thing left to do is to get those navbar images to show up right. Please look into this thoroughly before requesting another review :ok_hand: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by bettercallazamat** [comment]
> # Hey team 👋
> I can see that you made an attempt to incoporate the changes I suggested in the last review, however, please consider looking closely at the screenshots or the original site itself as the main video controls are still not arranged properly and at the moment your nav bar icons are incomplete and not showing up.
> 
> Make these changes and request another review! I wish you the best and see you at the top 🥇
> 
> ##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by nikasulo** [comment]
# Nice work making the changes @bettercallazamat and @bertil291utn 
Your attention to detail is top of the line and I wish you all the best in your subsequent projects and see you at the top! :rocket:

Please wait for the next TSE to give you an approval to merge :+1:

**Review by mosesogwo — APPROVED** [review]
**Hi team. Good job. Your project is approved :heavy_check_mark:**

You can now merge to master.

**Cheers:stars:**

**Pull request merged**
